### ISSUE TITLE
Toolbar missing on Mac

### ISSUE THREAD

**Issue by lriazy** [Cardiac-MR-Group-Lund/segment-open#10]
### Steps to reproduce

Open MATLAB R2018a
type "segment" to run segment

### Expected behavior

Toolbars to appear as in manual

### Actual behavior

The part of the toolbar below "LV" is missing. Tools can be reached by toggling with space, but in a very uncoordinated way.

### Details
Version/commit: 

Link to data set used: 
<img width="993" alt="grafik" src="https://user-images.githubusercontent.com/35132934/99665769-5cfe4600-2a6a-11eb-9ae3-de7030bc0724.png">

**Comment by lriazy** [comment]
This error was thrown:

Caught error:
MATLAB:UndefinedFunction
Undefined function or variable 'foregroundcolor'.
Stack:
segpref.m line 201 in setbackgroundcolor
segpref.m line 25 in segpref
maingui.m line 1209 in maingui.init
segment_main.m line 113 in initializesegment
segment_main.m line 38 in segment_main
segment.m line 9 in segment

**Comment by johannestoger** [comment]
Hi, segment-open supports only Matlab **R2014a**. Newer versions will not work.

**Comment by lriazy** [comment]
Thank you for your fast reply. Do you think I might be able to "hack" the GUI to make it work? I only need LV function, so I could delete the tabbed display, if that is the only problem.

**Comment by lriazy** [comment]
It worked! I replaced g.Handles.configiconholder with g.Handles.permanenticonholder and put the lv function elements in the top level toolbar in place of functions that I don't need. 

<img width="549" alt="grafik" src="https://user-images.githubusercontent.com/35132934/99674327-334b1c00-2a76-11eb-9100-ff0d2319a1ae.png">

**Comment by johannestoger** [comment]
OK, great! I would still strongly recommend **R2014a** though, there are many other things that could break.

**Comment by johannestoger** [comment]
Hi, we just pushed a new version supporting Matlab **R2019a**.
