### ISSUE TITLE
AYUDA PARA INSTALACION 

### ISSUE THREAD

**Issue by THOR22q** [Cardiac-MR-Group-Lund/segment-open#13]
### Details
Version/commit: 
Link to data set used: 

NO PUEDO HACER LA COMPILACION ME PODRIAN AYUDAR POR FAVOR.

**Comment by johannestoger** [comment]
Hi, I machine-translated your message to English as follows: "I CAN'T DO THE COMPILATION CAN YOU HELP ME PLEASE", I hope this is correct.

Please read the terms and conditions on the main page of the repository (README.md). We do not support (nor does the license allow) compiling segment-open. The recommendation is to run it through Matlab (preferably R2019a).
