### ISSUE TITLE
How to processing 4dflow files of SImmen,

### ISSUE THREAD

**Issue by foxet** [Cardiac-MR-Group-Lund/segment-open#3]
### Steps to reproduce
want to process 4dflow files of simmens  and save as .case
### Expected behavior
processing  three sets of phase images(3  directions) and produce one velocity file 
### Details
Version/commit: 
Link to data set used:

**Comment by johannestoger** [comment]
Hi foxet,

Can you please tell us a bit more about what you tried, what your files look like and what kind of results you get? One thing to try is to load all four directories of 4D Flow data at once (magnitude + 3 velocity folders)  at the same time in the open file dialog.
