### ISSUE TITLE
Loading flow image from 4D Flow

### ISSUE THREAD

**Issue by piolin798** [Cardiac-MR-Group-Lund/segment-open#4]
### Steps to reproduce
Load flow image from 4D flow (3 dicom stacks, one for each velocity direction) and generate magnitude image.
### Expected behavior
Load and display flow image.
### Actual behavior
I get the following message "Error:Some phases have more images than others"
### Details
Version/commit: 
Link to data set used:

**Comment by johannestoger** [comment]
Thanks for reporting this issue. To investigate further we need access to a data set that triggers the issue. Would it be possible for you to send that?

**Comment by johannestoger** [comment]
Hi again piolin798, I'm closing this for now since you haven't replied. Please feel free to reopen it if you still need help.
