### ISSUE TITLE
Question :Calculate T1. 

### ISSUE THREAD

**Issue by zhangluwei1997** [Cardiac-MR-Group-Lund/segment-open#7]
Hello ! I am studying MRI, I want to calculate T1 from the image of Dicom. I want to study your 
  code to know how to calculate it. Could you tell me which files has  the algorithm of 
  calculating T1 time ? 

  Thanks !

**Comment by johannestoger** [comment]
Hi, the T1 analysis is available in the toolbar, see image below.

![image](https://user-images.githubusercontent.com/2676014/58253798-8650ef80-7d69-11e9-9b11-0614b41cd666.png)

Unfortunately the T1, T2 and T2* analysis is one of the parts of Segment that Medviso AB (the company behind Segment) has decided to not publish as an m-file. Instead, it is available only as an encrypted p-file. I will ask the company if it would be possible to publish this code.

**Comment by zhangluwei1997** [comment]
Thank you very much!

**Comment by johannestoger** [comment]
Hi, I talked to Medviso and they have decided to not share that part of the code. If you have any specific questions, you can add them as an issue here and I'll ask the Medviso engineers to have a look at it.
